version: "2"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "docker_db"
    volumes:
      - ./db_data:/var/lib/postgresql
  web:
    build:
      context: .
    ports:
      - "7001:7001"
    depends_on:
      - db
